apiVersion: v1
kind: Deployment
metadata:
  name: hpa-deploy
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp
  template:
    metadata:
      name: httpd-pod
      labels: 
        app: myapp
    spec: 
      containers:
        - name: cont1
          image: httpd
          ports: 
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          
