apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-pod
spec:
  scaleTargetRef:
    kind: Deployment 
    name: hpa-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50