apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      name: mginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-rc
        image: nginx
        ports:
        - containerPort: 80       
