apiVersion: v1
kind: pod 
metadata:
  name: redis-pod-secret-env
spec:
  containers:
    - name: redis-container
      image: redis
      env:
      - name: SECRET_USERNAME 
        valueFrom: 
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password 
  restartPolicy: Never