apiVersion: v1 
kind: Service
metadata:
  name: redis-slave-svc
  labels:
    app: redis
    tier: frontend
spec:
  selector:
    app: redis
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
    

