apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-master-deployment
  labels:
    app: redis 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis
      role: master 
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: redis-container
        image: k8s.gcr.io./redis:e2e
        ports:
        - containerPort: 6379