apiVersion: v1 
kind: Service
metadata:
  name: redis-slave-svc
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  selector:
    app: redis
    role: slave
    tier: backend
  type: ClusterIP
  ports:
    - port: 6379
    

