apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-slave-deployment
  labels:
    app: redis 
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: redis-slave-container
        image: gcr.io/google_samples/gb-redisslave:v1
        ports:
        - containerPort: 6379