apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-svc
  labels:
    name: nginx-app
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80